/**
 * InsightsPanel - Displays auto-generated stats and AI-powered summaries
 */

import { useState, useMemo } from 'react';
import { Sparkles, RefreshCw, BarChart2, Lightbulb, TrendingUp, AlertCircle, ExternalLink, Copy, Check, Download } from 'lucide-react';
import { parseConversationStats, hasEnoughContent, formatNumber, backendStatsToConversationStats, type ConversationStats, type BackendArticleStats } from '../../utils/insightsParser';
import { generateInsights, type ChatInsights } from '../../services/auspexService';
import { extractErrorMessage } from '../../services/api';
import { AIDisclosureFooter } from '../AIDisclosureFooter';

interface InsightsPanelProps {
  messages: Array<{ role: string; content: string }>;
  chatId: number | null;
  backendArticleStats?: BackendArticleStats | null;
}

export function InsightsPanel({ messages, chatId, backendArticleStats }: InsightsPanelProps) {
  const [aiInsights, setAiInsights] = useState<ChatInsights | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedLinks, setCopiedLinks] = useState(false);

  // Use backend stats if available, otherwise parse from messages
  const stats = useMemo<ConversationStats>(() => {
    if (backendArticleStats) {
      return backendStatsToConversationStats(backendArticleStats);
    }
    return parseConversationStats(messages);
  }, [backendArticleStats, messages]);

  const hasContent = hasEnoughContent(messages);

  // Copy all article links to clipboard
  const handleCopyLinks = async () => {
    if (stats.sourceLinks.length === 0) return;
    const linksText = stats.sourceLinks.map(s => `${s.name}\n${s.url}`).join('\n\n');
    await navigator.clipboard.writeText(linksText);
    setCopiedLinks(true);
    setTimeout(() => setCopiedLinks(false), 2000);
  };

  // Export summary as markdown
  const handleExportMarkdown = () => {
    if (!aiInsights) return;

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric'
    });
    const timeStr = now.toLocaleTimeString('en-US', {
      hour: '2-digit', minute: '2-digit'
    });

    let markdown = `# Auspex Intelligence Summary\n\n`;
    markdown += `**Generated:** ${dateStr} at ${timeStr}\n\n`;
    markdown += `---\n\n`;

    // Key Themes
    if (aiInsights.key_themes && aiInsights.key_themes.length > 0) {
      markdown += `## Key Themes\n\n`;
      aiInsights.key_themes.forEach(theme => {
        markdown += `- ${theme}\n`;
      });
      markdown += `\n`;
    }

    // Main Findings
    if (aiInsights.main_findings && aiInsights.main_findings.length > 0) {
      markdown += `## Main Findings\n\n`;
      aiInsights.main_findings.forEach(finding => {
        markdown += `- ${finding}\n`;
      });
      markdown += `\n`;
    }

    // Sentiment Overview
    if (aiInsights.sentiment_overview) {
      markdown += `## Sentiment Overview\n\n`;
      markdown += `${aiInsights.sentiment_overview}\n\n`;
    }

    // Notable Quotes/Datapoints
    if (aiInsights.notable_quotes && aiInsights.notable_quotes.length > 0) {
      markdown += `## Notable Datapoints\n\n`;
      aiInsights.notable_quotes.forEach(quote => {
        markdown += `> "${quote}"\n\n`;
      });
    }

    // Data Coverage
    if (aiInsights.data_coverage) {
      markdown += `## Data Coverage\n\n`;
      if (aiInsights.data_coverage.articles_discussed > 0) {
        markdown += `- **Articles Analyzed:** ${aiInsights.data_coverage.articles_discussed}\n`;
      }
      if (aiInsights.data_coverage.sources_mentioned > 0) {
        markdown += `- **Sources:** ${aiInsights.data_coverage.sources_mentioned}\n`;
      }
      if (aiInsights.data_coverage.time_period && aiInsights.data_coverage.time_period !== 'not specified') {
        markdown += `- **Time Period:** ${aiInsights.data_coverage.time_period}\n`;
      }
      markdown += `\n`;
    }

    // Article Sources
    if (stats.sourceLinks && stats.sourceLinks.length > 0) {
      markdown += `## Sources\n\n`;
      stats.sourceLinks.forEach(source => {
        markdown += `### ${source.name}\n`;
        markdown += `${source.url}\n\n`;
      });
    }

    markdown += `---\n\n`;
    markdown += `*Generated by Auspex Intelligence Platform*\n`;

    // Download the file
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `auspex-summary-${now.toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleGenerateInsights = async () => {
    if (!chatId) return;

    setIsGenerating(true);
    setError(null);

    try {
      const response = await generateInsights(chatId);
      if (response.insights) {
        setAiInsights(response.insights);
      } else if (response.message) {
        setError(extractErrorMessage(response.message, 'Failed to generate insights'));
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate insights');
    } finally {
      setIsGenerating(false);
    }
  };

  // Empty state
  if (!hasContent) {
    return (
      <div className="text-center py-8 text-gray-500">
        <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
        <h3 className="text-sm font-medium text-gray-600 dark:text-gray-300 mb-1">
          AI Insights
        </h3>
        <p className="text-xs text-gray-500">
          Insights will appear as you chat with Auspex
        </p>
      </div>
    );
  }

  const totalSentiment = stats.sentimentBreakdown.positive + stats.sentimentBreakdown.neutral +
                         stats.sentimentBreakdown.negative + stats.sentimentBreakdown.mixed;

  // Check if we have any parsed stats (articles or sentiment data)
  const hasParsedStats = stats.totalArticles > 0 || totalSentiment > 0;
  const hasArticleLinks = stats.sourceLinks && stats.sourceLinks.length > 0;

  return (
    <div className="space-y-4">
      {/* Article Links Section - Show actual URLs users can click/copy */}
      {hasArticleLinks && (
        <div className="bg-white dark:bg-gray-700 rounded-lg p-3 border border-gray-200 dark:border-gray-600">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-300 uppercase flex items-center gap-1">
              <ExternalLink className="w-3 h-3" />
              Article Sources ({stats.sourceLinks.length})
            </h4>
            <button
              onClick={handleCopyLinks}
              className="flex items-center gap-1 px-2 py-1 text-xs text-gray-500 hover:text-gray-700 dark:text-gray-300 dark:hover:text-gray-200 border border-gray-300 dark:border-gray-600 rounded hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
              title="Copy all links"
            >
              {copiedLinks ? <Check className="w-3 h-3 text-green-500" /> : <Copy className="w-3 h-3" />}
              {copiedLinks ? 'Copied!' : 'Copy All'}
            </button>
          </div>
          <div className="max-h-48 overflow-y-auto space-y-1.5">
            {stats.sourceLinks.map((source, i) => (
              <a
                key={i}
                href={source.url}
                target="_blank"
                rel="noopener noreferrer"
                className="block text-xs p-2 bg-gray-50 dark:bg-gray-800 rounded hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors group"
                title={source.url}
              >
                <div className="text-gray-700 dark:text-gray-400 truncate group-hover:text-pink-600 dark:group-hover:text-pink-400">
                  {source.name}
                </div>
                <div className="text-[10px] text-gray-500 truncate mt-0.5">
                  {source.url}
                </div>
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Parsed Stats Section - Only shown if we found stats */}
      {hasParsedStats && (
        <div className="bg-white dark:bg-gray-700 rounded-lg p-3 border border-gray-200 dark:border-gray-600">
          <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-300 uppercase mb-3 flex items-center gap-1">
            <BarChart2 className="w-3 h-3" />
            Analysis Stats
          </h4>

          {stats.totalArticles > 0 && (
            <div className="text-center p-2 bg-gray-50 dark:bg-gray-800 rounded">
              <div className="text-lg font-bold text-green-500">{formatNumber(stats.totalArticles)}</div>
              <div className="text-xs text-gray-500">Articles Analyzed</div>
            </div>
          )}

          {/* Sentiment Breakdown */}
          {totalSentiment > 0 && (
            <div className="mt-3">
              <h5 className="text-xs text-gray-500 mb-1.5 flex items-center gap-1">
                <TrendingUp className="w-3 h-3" />
                Sentiment Distribution
              </h5>
              <div className="flex gap-0.5 h-5 rounded overflow-hidden">
                {stats.sentimentBreakdown.positive > 0 && (
                  <div
                    className="bg-green-500 flex items-center justify-center text-white text-[10px] font-medium"
                    style={{ width: `${(stats.sentimentBreakdown.positive / totalSentiment) * 100}%` }}
                    title={`Positive: ${stats.sentimentBreakdown.positive}`}
                  >
                    {stats.sentimentBreakdown.positive > totalSentiment * 0.15 && stats.sentimentBreakdown.positive}
                  </div>
                )}
                {stats.sentimentBreakdown.neutral > 0 && (
                  <div
                    className="bg-gray-400 flex items-center justify-center text-white text-[10px] font-medium"
                    style={{ width: `${(stats.sentimentBreakdown.neutral / totalSentiment) * 100}%` }}
                    title={`Neutral: ${stats.sentimentBreakdown.neutral}`}
                  >
                    {stats.sentimentBreakdown.neutral > totalSentiment * 0.15 && stats.sentimentBreakdown.neutral}
                  </div>
                )}
                {stats.sentimentBreakdown.negative > 0 && (
                  <div
                    className="bg-red-500 flex items-center justify-center text-white text-[10px] font-medium"
                    style={{ width: `${(stats.sentimentBreakdown.negative / totalSentiment) * 100}%` }}
                    title={`Negative: ${stats.sentimentBreakdown.negative}`}
                  >
                    {stats.sentimentBreakdown.negative > totalSentiment * 0.15 && stats.sentimentBreakdown.negative}
                  </div>
                )}
                {stats.sentimentBreakdown.mixed > 0 && (
                  <div
                    className="bg-amber-500 flex items-center justify-center text-white text-[10px] font-medium"
                    style={{ width: `${(stats.sentimentBreakdown.mixed / totalSentiment) * 100}%` }}
                    title={`Mixed: ${stats.sentimentBreakdown.mixed}`}
                  >
                    {stats.sentimentBreakdown.mixed > totalSentiment * 0.15 && stats.sentimentBreakdown.mixed}
                  </div>
                )}
              </div>
              <div className="flex justify-between mt-1 text-[10px] text-gray-500">
                <span>Positive</span>
                <span>Neutral</span>
                <span>Negative</span>
              </div>
            </div>
          )}

        </div>
      )}

      {/* AI Summary Section */}
      <div className="bg-white dark:bg-gray-700 rounded-lg p-3 border border-gray-200 dark:border-gray-600">
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-300 uppercase flex items-center gap-1">
            <Lightbulb className="w-3 h-3" />
            AI Summary
          </h4>
          <div className="flex items-center gap-1">
            {aiInsights && (
              <button
                onClick={handleExportMarkdown}
                className="flex items-center gap-1 px-2 py-1 text-xs text-gray-500 hover:text-gray-700 dark:text-gray-300 dark:hover:text-gray-200 border border-gray-300 dark:border-gray-600 rounded hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
                title="Export as Markdown"
              >
                <Download className="w-3 h-3" />
                Export
              </button>
            )}
            <button
              onClick={handleGenerateInsights}
              disabled={isGenerating || !chatId}
              className="flex items-center gap-1 px-2 py-1 text-xs bg-pink-500 text-white rounded hover:bg-pink-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <RefreshCw className={`w-3 h-3 ${isGenerating ? 'animate-spin' : ''}`} />
              {isGenerating ? 'Analyzing...' : 'Summarize'}
            </button>
          </div>
        </div>

        {error && (
          <div className="flex items-center gap-2 text-xs text-red-500 mb-2 p-2 bg-red-50 dark:bg-red-900/20 rounded">
            <AlertCircle className="w-3 h-3 flex-shrink-0" />
            {error}
          </div>
        )}

        {aiInsights ? (
          <div className="space-y-3 text-sm">
            {/* Key Themes */}
            {aiInsights.key_themes && aiInsights.key_themes.length > 0 && (
              <div>
                <h5 className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Key Themes</h5>
                <div className="flex flex-wrap gap-1">
                  {aiInsights.key_themes.map((theme, i) => (
                    <span
                      key={i}
                      className="px-2 py-0.5 bg-pink-100 dark:bg-pink-900/30 text-pink-700 dark:text-pink-300 rounded text-xs"
                    >
                      {theme}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Main Findings */}
            {aiInsights.main_findings && aiInsights.main_findings.length > 0 && (
              <div>
                <h5 className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Main Findings</h5>
                <ul className="list-disc list-inside text-gray-600 dark:text-gray-300 text-xs space-y-0.5">
                  {aiInsights.main_findings.slice(0, 4).map((finding, i) => (
                    <li key={i} className="leading-tight">{finding}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Sentiment Overview */}
            {aiInsights.sentiment_overview && (
              <div>
                <h5 className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Sentiment</h5>
                <p className="text-xs text-gray-600 dark:text-gray-300 leading-relaxed">
                  {aiInsights.sentiment_overview}
                </p>
              </div>
            )}

            {/* Notable Quotes */}
            {aiInsights.notable_quotes && aiInsights.notable_quotes.length > 0 && (
              <div>
                <h5 className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Notable Datapoints</h5>
                <ul className="text-gray-600 dark:text-gray-300 text-xs space-y-1">
                  {aiInsights.notable_quotes.slice(0, 3).map((quote, i) => (
                    <li key={i} className="leading-tight italic border-l-2 border-pink-300 pl-2">"{quote}"</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Data Coverage */}
            {aiInsights.data_coverage && (
              <div className="pt-2 border-t border-gray-200 dark:border-gray-600">
                <h5 className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Data Coverage</h5>
                <div className="grid grid-cols-3 gap-1 text-center">
                  {aiInsights.data_coverage.articles_discussed > 0 && (
                    <div className="p-1 bg-gray-50 dark:bg-gray-800 rounded">
                      <div className="text-sm font-semibold text-gray-700 dark:text-gray-400">
                        {aiInsights.data_coverage.articles_discussed}
                      </div>
                      <div className="text-[10px] text-gray-500">Articles</div>
                    </div>
                  )}
                  {aiInsights.data_coverage.sources_mentioned > 0 && (
                    <div className="p-1 bg-gray-50 dark:bg-gray-800 rounded">
                      <div className="text-sm font-semibold text-gray-700 dark:text-gray-400">
                        {aiInsights.data_coverage.sources_mentioned}
                      </div>
                      <div className="text-[10px] text-gray-500">Sources</div>
                    </div>
                  )}
                  {aiInsights.data_coverage.time_period && aiInsights.data_coverage.time_period !== 'not specified' && (
                    <div className="p-1 bg-gray-50 dark:bg-gray-800 rounded col-span-full">
                      <div className="text-xs text-gray-600 dark:text-gray-300">
                        {aiInsights.data_coverage.time_period}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        ) : (
          <p className="text-xs text-gray-500 text-center py-4">
            Click "Summarize" to create an AI summary of your conversation
          </p>
        )}
      </div>

      {/* EU AI Act Art. 50 visible disclosure */}
      <AIDisclosureFooter
        dashboardName="Auspex Insights"
        aiTools={['GPT-4']}
        purpose="To summarize conversation themes, findings, and sentiment from analyzed sources"
      />
    </div>
  );
}
