"""add_pgvector_support

Revision ID: 8eadb2079747
Revises: 1745b4f22f68
Create Date: 2025-10-16 12:36:15.799250

Adds pgvector extension support and embedding column to articles table.
This migration:
1. Creates pgvector extension (if not exists - requires superuser)
2. Adds embedding vector(1536) column to articles table
3. Creates IVFFlat index for efficient vector similarity searches
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8eadb2079747'
down_revision: Union[str, None] = '1745b4f22f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add pgvector support to articles table."""
    # Note: Extension creation requires superuser privileges
    # This should already be done, but we include it for completeness
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # Add embedding column using pgvector's vector type (1536 dimensions for OpenAI text-embedding-3-small)
    # We use raw SQL since pgvector doesn't have native SQLAlchemy type
    op.execute("""
        ALTER TABLE articles
        ADD COLUMN embedding vector(1536)
    """)

    # Add comment to document the column
    op.execute("""
        COMMENT ON COLUMN articles.embedding IS
        'Vector embedding (1536-dim) generated by OpenAI text-embedding-3-small model for semantic search'
    """)

    # Note: IVFFlat index creation will be done after embeddings are populated
    # This is handled in the data migration script


def downgrade() -> None:
    """Remove pgvector support from articles table."""
    # Drop the index first (if exists)
    op.execute('DROP INDEX IF EXISTS articles_embedding_idx')

    # Drop the embedding column
    op.drop_column('articles', 'embedding')

    # Note: We don't drop the extension as other tables might use it
    # If you want to completely remove pgvector:
    # op.execute('DROP EXTENSION IF EXISTS vector')
