"""Initial database structure.

Revision ID: c83125fe7cb0
Revises: 
Create Date: 2025-08-19 12:52:00.684567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83125fe7cb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('version_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('analysis_depth', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_versions_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('version_data', sa.Text(), nullable=False),
    sa.Column('cache_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('accessed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('idx_accessed_at', 'analysis_versions_v2', ['accessed_at'], unique=False)
    op.create_index('idx_cache_key_created', 'analysis_versions_v2', ['cache_key', 'created_at'], unique=False)
    op.create_index('idx_topic_created', 'analysis_versions_v2', ['topic', 'created_at'], unique=False)
    op.create_table('articles',
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('news_source', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('future_signal', sa.Text(), nullable=True),
    sa.Column('future_signal_explanation', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('sentiment_explanation', sa.Text(), nullable=True),
    sa.Column('time_to_impact', sa.Text(), nullable=True),
    sa.Column('time_to_impact_explanation', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('driver_type', sa.Text(), nullable=True),
    sa.Column('driver_type_explanation', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.Column('bias', sa.Text(), nullable=True),
    sa.Column('factual_reporting', sa.Text(), nullable=True),
    sa.Column('mbfc_credibility_rating', sa.Text(), nullable=True),
    sa.Column('bias_source', sa.Text(), nullable=True),
    sa.Column('bias_country', sa.Text(), nullable=True),
    sa.Column('press_freedom', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Text(), nullable=True),
    sa.Column('topic_alignment_score', sa.REAL(), nullable=True),
    sa.Column('keyword_relevance_score', sa.REAL(), nullable=True),
    sa.Column('confidence_score', sa.REAL(), nullable=True),
    sa.Column('overall_match_explanation', sa.Text(), nullable=True),
    sa.Column('extracted_article_topics', sa.Text(), nullable=True),
    sa.Column('extracted_article_keywords', sa.Text(), nullable=True),
    sa.Column('ingest_status', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.REAL(), nullable=True),
    sa.Column('quality_issues', sa.Text(), nullable=True),
    sa.Column('auto_ingested', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_index('idx_articles_auto_ingested', 'articles', ['auto_ingested'], unique=False)
    op.create_index('idx_articles_bias', 'articles', ['bias'], unique=False)
    op.create_index('idx_articles_factual_reporting', 'articles', ['factual_reporting'], unique=False)
    op.create_index('idx_articles_ingest_status', 'articles', ['ingest_status'], unique=False)
    op.create_index('idx_articles_quality_score', 'articles', ['quality_score'], unique=False)
    op.create_index('idx_articles_uri', 'articles', ['uri'], unique=True)
    op.create_table('articles_scenario_1',
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('news_source', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.Column('topic_sentiment', sa.Text(), nullable=True),
    sa.Column('topic_sentiment_explanation', sa.Text(), nullable=True),
    sa.Column('sensitivity_level', sa.Text(), nullable=True),
    sa.Column('sensitivity_level_explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_table('building_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feed_keyword_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keyword_monitor_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.Integer(), nullable=False),
    sa.Column('search_fields', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('sort_by', sa.Text(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_request_limit', sa.Integer(), nullable=False),
    sa.Column('search_date_range', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('auto_ingest_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_relevance_threshold', sa.REAL(), nullable=False),
    sa.Column('quality_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_save_approved_only', sa.Boolean(), nullable=False),
    sa.Column('default_llm_model', sa.Text(), nullable=False),
    sa.Column('llm_temperature', sa.REAL(), nullable=False),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_monitor_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_check_time', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediabias',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('bias', sa.Text(), nullable=True),
    sa.Column('factual_reporting', sa.Text(), nullable=True),
    sa.Column('press_freedom', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Text(), nullable=True),
    sa.Column('mbfc_credibility_rating', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_index('idx_mediabias_source', 'mediabias', ['source'], unique=False)
    op.create_table('mediabias_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.CheckConstraint('id = 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_bias_arena_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benchmark_model', sa.Text(), nullable=False),
    sa.Column('selected_models', sa.Text(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bias_arena_runs_rounds', 'model_bias_arena_runs', ['rounds', 'current_round'], unique=False)
    op.create_index('idx_bias_arena_runs_status', 'model_bias_arena_runs', ['status'], unique=False)
    op.create_table('newsletter_prompts',
    sa.Column('content_type_id', sa.Text(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('content_type_id')
    )
    op.create_table('oauth_allowlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('added_by', sa.Text(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('oauth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'provider')
    )
    op.create_index('idx_oauth_users_active', 'oauth_users', ['is_active'], unique=False)
    op.create_index('idx_oauth_users_email_provider', 'oauth_users', ['email', 'provider'], unique=False)
    op.create_index('idx_oauth_users_provider', 'oauth_users', ['provider'], unique=False)
    op.create_table('organizational_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('organization_type', sa.Text(), nullable=True),
    sa.Column('key_concerns', sa.Text(), nullable=True),
    sa.Column('strategic_priorities', sa.Text(), nullable=True),
    sa.Column('risk_tolerance', sa.Text(), nullable=True),
    sa.Column('innovation_appetite', sa.Text(), nullable=True),
    sa.Column('decision_making_style', sa.Text(), nullable=True),
    sa.Column('stakeholder_focus', sa.Text(), nullable=True),
    sa.Column('competitive_landscape', sa.Text(), nullable=True),
    sa.Column('regulatory_environment', sa.Text(), nullable=True),
    sa.Column('custom_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_org_profiles_default', 'organizational_profiles', ['is_default'], unique=False)
    op.create_index('idx_org_profiles_industry', 'organizational_profiles', ['industry'], unique=False)
    op.create_index('idx_org_profiles_name', 'organizational_profiles', ['name'], unique=False)
    op.create_table('podcasts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('article_table', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_table'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings_podcasts',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trend_consistency_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('consistency_score', sa.REAL(), nullable=False),
    sa.Column('comparison_count', sa.Integer(), nullable=True),
    sa.Column('detailed_metrics', sa.Text(), nullable=True),
    sa.Column('analysis_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consistency_topic_date', 'trend_consistency_metrics', ['topic', 'analysis_date'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.Column('completed_onboarding', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('article_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_uri', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['article_uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auspex_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auspex_chats_topic', 'auspex_chats', ['topic'], unique=False)
    op.create_index('idx_auspex_chats_user_id', 'auspex_chats', ['user_id'], unique=False)
    op.create_table('auspex_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_created', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_created'], ['users.username'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_auspex_prompts_is_default', 'auspex_prompts', ['is_default'], unique=False)
    op.create_index('idx_auspex_prompts_name', 'auspex_prompts', ['name'], unique=False)
    op.create_table('feed_group_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_range_days', sa.Integer(), nullable=True),
    sa.Column('custom_start_date', sa.Text(), nullable=True),
    sa.Column('custom_end_date', sa.Text(), nullable=True),
    sa.Column('search_settings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['feed_keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('author_handle', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('engagement_metrics', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('mentions', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['feed_keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'group_id')
    )
    op.create_index('idx_feed_items_group_id', 'feed_items', ['group_id'], unique=False)
    op.create_index('idx_feed_items_is_hidden', 'feed_items', ['is_hidden'], unique=False)
    op.create_index('idx_feed_items_is_starred', 'feed_items', ['is_starred'], unique=False)
    op.create_index('idx_feed_items_publication_date', 'feed_items', ['publication_date'], unique=False)
    op.create_index('idx_feed_items_source_type', 'feed_items', ['source_type'], unique=False)
    op.create_table('keyword_article_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_uri', sa.Text(), nullable=False),
    sa.Column('keyword_ids', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_uri', 'group_id')
    )
    op.create_table('model_bias_arena_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('article_uri', sa.Text(), nullable=False),
    sa.Column('article_title', sa.Text(), nullable=True),
    sa.Column('article_summary', sa.Text(), nullable=True),
    sa.Column('selected_for_benchmark', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['article_uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['model_bias_arena_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'article_uri')
    )
    op.create_index('idx_bias_arena_articles_run_id', 'model_bias_arena_articles', ['run_id'], unique=False)
    op.create_table('model_bias_arena_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('article_uri', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('bias_score', sa.REAL(), nullable=True),
    sa.Column('confidence_score', sa.REAL(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sentiment_explanation', sa.Text(), nullable=True),
    sa.Column('future_signal_explanation', sa.Text(), nullable=True),
    sa.Column('time_to_impact_explanation', sa.Text(), nullable=True),
    sa.Column('driver_type_explanation', sa.Text(), nullable=True),
    sa.Column('category_explanation', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('future_signal', sa.Text(), nullable=True),
    sa.Column('time_to_impact', sa.Text(), nullable=True),
    sa.Column('driver_type', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('political_bias', sa.Text(), nullable=True),
    sa.Column('political_bias_explanation', sa.Text(), nullable=True),
    sa.Column('factuality', sa.Text(), nullable=True),
    sa.Column('factuality_explanation', sa.Text(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['model_bias_arena_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bias_arena_results_factuality', 'model_bias_arena_results', ['factuality'], unique=False)
    op.create_index('idx_bias_arena_results_model', 'model_bias_arena_results', ['model_name'], unique=False)
    op.create_index('idx_bias_arena_results_political_bias', 'model_bias_arena_results', ['political_bias'], unique=False)
    op.create_index('idx_bias_arena_results_round', 'model_bias_arena_results', ['run_id', 'round_number'], unique=False)
    op.create_index('idx_bias_arena_results_run_id', 'model_bias_arena_results', ['run_id'], unique=False)
    op.create_table('monitored_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'keyword')
    )
    op.create_table('oauth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['oauth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('raw_articles',
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uri')
    )
    op.create_table('scenario_blocks',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('building_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_block_id'], ['building_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'building_block_id')
    )
    op.create_table('user_feed_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['feed_keyword_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_feed_subscriptions_group_id', 'user_feed_subscriptions', ['group_id'], unique=False)
    op.create_table('auspex_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['auspex_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auspex_messages_chat_id', 'auspex_messages', ['chat_id'], unique=False)
    op.create_index('idx_auspex_messages_role', 'auspex_messages', ['role'], unique=False)
    op.create_table('keyword_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('article_uri', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_uri'], ['articles.uri'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['monitored_keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'article_uri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_alerts')
    op.drop_index('idx_auspex_messages_role', table_name='auspex_messages')
    op.drop_index('idx_auspex_messages_chat_id', table_name='auspex_messages')
    op.drop_table('auspex_messages')
    op.drop_index('idx_user_feed_subscriptions_group_id', table_name='user_feed_subscriptions')
    op.drop_table('user_feed_subscriptions')
    op.drop_table('scenario_blocks')
    op.drop_table('raw_articles')
    op.drop_table('oauth_sessions')
    op.drop_table('monitored_keywords')
    op.drop_index('idx_bias_arena_results_run_id', table_name='model_bias_arena_results')
    op.drop_index('idx_bias_arena_results_round', table_name='model_bias_arena_results')
    op.drop_index('idx_bias_arena_results_political_bias', table_name='model_bias_arena_results')
    op.drop_index('idx_bias_arena_results_model', table_name='model_bias_arena_results')
    op.drop_index('idx_bias_arena_results_factuality', table_name='model_bias_arena_results')
    op.drop_table('model_bias_arena_results')
    op.drop_index('idx_bias_arena_articles_run_id', table_name='model_bias_arena_articles')
    op.drop_table('model_bias_arena_articles')
    op.drop_table('keyword_article_matches')
    op.drop_index('idx_feed_items_source_type', table_name='feed_items')
    op.drop_index('idx_feed_items_publication_date', table_name='feed_items')
    op.drop_index('idx_feed_items_is_starred', table_name='feed_items')
    op.drop_index('idx_feed_items_is_hidden', table_name='feed_items')
    op.drop_index('idx_feed_items_group_id', table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_table('feed_group_sources')
    op.drop_index('idx_auspex_prompts_name', table_name='auspex_prompts')
    op.drop_index('idx_auspex_prompts_is_default', table_name='auspex_prompts')
    op.drop_table('auspex_prompts')
    op.drop_index('idx_auspex_chats_user_id', table_name='auspex_chats')
    op.drop_index('idx_auspex_chats_topic', table_name='auspex_chats')
    op.drop_table('auspex_chats')
    op.drop_table('article_annotations')
    op.drop_table('users')
    op.drop_index('idx_consistency_topic_date', table_name='trend_consistency_metrics')
    op.drop_table('trend_consistency_metrics')
    op.drop_table('settings_podcasts')
    op.drop_table('scenarios')
    op.drop_table('podcasts')
    op.drop_index('idx_org_profiles_name', table_name='organizational_profiles')
    op.drop_index('idx_org_profiles_industry', table_name='organizational_profiles')
    op.drop_index('idx_org_profiles_default', table_name='organizational_profiles')
    op.drop_table('organizational_profiles')
    op.drop_index('idx_oauth_users_provider', table_name='oauth_users')
    op.drop_index('idx_oauth_users_email_provider', table_name='oauth_users')
    op.drop_index('idx_oauth_users_active', table_name='oauth_users')
    op.drop_table('oauth_users')
    op.drop_table('oauth_allowlist')
    op.drop_table('newsletter_prompts')
    op.drop_index('idx_bias_arena_runs_status', table_name='model_bias_arena_runs')
    op.drop_index('idx_bias_arena_runs_rounds', table_name='model_bias_arena_runs')
    op.drop_table('model_bias_arena_runs')
    op.drop_table('migrations')
    op.drop_table('mediabias_settings')
    op.drop_index('idx_mediabias_source', table_name='mediabias')
    op.drop_table('mediabias')
    op.drop_table('keyword_monitor_status')
    op.drop_table('keyword_monitor_settings')
    op.drop_table('keyword_groups')
    op.drop_table('feed_keyword_groups')
    op.drop_table('building_blocks')
    op.drop_table('articles_scenario_1')
    op.drop_index('idx_articles_uri', table_name='articles')
    op.drop_index('idx_articles_quality_score', table_name='articles')
    op.drop_index('idx_articles_ingest_status', table_name='articles')
    op.drop_index('idx_articles_factual_reporting', table_name='articles')
    op.drop_index('idx_articles_bias', table_name='articles')
    op.drop_index('idx_articles_auto_ingested', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_topic_created', table_name='analysis_versions_v2')
    op.drop_index('idx_cache_key_created', table_name='analysis_versions_v2')
    op.drop_index('idx_accessed_at', table_name='analysis_versions_v2')
    op.drop_table('analysis_versions_v2')
    op.drop_table('analysis_versions')
    # ### end Alembic commands ###
