/**
 * Newsletter Tune Modal - Multi-step prompt editor for Newsletter Generator
 *
 * Allows editing of 2 agent prompts:
 * 1. Deep Dive - in-depth analysis with consensus evaluation
 * 2. Main Newsletter - full newsletter generation with all sections
 *
 * Following the same pattern as SIOTuneModal
 */

import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle
} from './ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Loader2, Save, RotateCcw, Zap, BookOpen, FileText, Settings2 } from 'lucide-react';
import { Alert, AlertDescription } from './ui/alert';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { Label } from './ui/label';

interface NewsletterAgent {
  id: string;
  name: string;
  description: string;
  content: string;
  metadata: Record<string, any>;
}

interface AvailableModel {
  name: string;
  provider?: string;
}

interface NewsletterTuneModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  // Config values from parent
  daysBack: number;
  deepDiveTopic: string;
  newsletterTitle: string;
  newsletterIntro: string;
  // Callbacks to update parent state
  onDaysBackChange: (value: number) => void;
  onDeepDiveTopicChange: (value: string) => void;
  onNewsletterTitleChange: (value: string) => void;
  onNewsletterIntroChange: (value: string) => void;
}

const AGENT_ICONS: Record<string, React.ReactNode> = {
  newsletter_deep_dive_agent: <Zap className="w-4 h-4" />,
  newsletter_main_agent: <BookOpen className="w-4 h-4" />
};

// User-friendly temperature presets
const CREATIVITY_PRESETS = [
  {
    value: '0.2',
    label: 'Precise',
    description: 'Highly focused and deterministic. Best for factual analysis.',
    color: 'bg-blue-100 text-blue-800'
  },
  {
    value: '0.3',
    label: 'Balanced',
    description: 'Mix of precision and variety. Good for most tasks.',
    color: 'bg-green-100 text-green-800'
  },
  {
    value: '0.5',
    label: 'Engaging',
    description: 'More varied responses. Good for newsletters.',
    color: 'bg-yellow-100 text-yellow-800'
  },
  {
    value: '0.7',
    label: 'Creative',
    description: 'Higher variety and creativity. May be less consistent.',
    color: 'bg-orange-100 text-orange-800'
  }
];

// Default models for each agent type
const DEFAULT_MODELS: Record<string, string> = {
  newsletter_deep_dive_agent: 'gpt-4.1',
  newsletter_main_agent: 'gpt-4.1'
};

// Default temperatures for each agent type
const DEFAULT_TEMPS: Record<string, string> = {
  newsletter_deep_dive_agent: '0.3',
  newsletter_main_agent: '0.5'
};

// Note: Section limits removed in v3.0 - sections are now dynamically generated by LLM

export function NewsletterTuneModal({
  open,
  onOpenChange,
  daysBack,
  deepDiveTopic,
  newsletterTitle,
  newsletterIntro,
  onDaysBackChange,
  onDeepDiveTopicChange,
  onNewsletterTitleChange,
  onNewsletterIntroChange
}: NewsletterTuneModalProps) {
  const [agents, setAgents] = useState<NewsletterAgent[]>([]);
  const [availableModels, setAvailableModels] = useState<AvailableModel[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  // Edited agent values (local state)
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [editedModels, setEditedModels] = useState<Record<string, string>>({});
  const [editedTemps, setEditedTemps] = useState<Record<string, string>>({});

  // Edited config values (local state)
  const [editedDaysBack, setEditedDaysBack] = useState(daysBack);
  const [editedDeepDive, setEditedDeepDive] = useState(deepDiveTopic);
  const [editedTitle, setEditedTitle] = useState(newsletterTitle);
  const [editedIntro, setEditedIntro] = useState(newsletterIntro);
  const [editedMaxArticles, setEditedMaxArticles] = useState(100);

  // Original config values (for comparison)
  const [originalConfig, setOriginalConfig] = useState({
    daysBack,
    deepDiveTopic,
    newsletterTitle,
    newsletterIntro,
    maxArticles: 100
  });

  const [activeAgent, setActiveAgent] = useState('newsletter_deep_dive_agent');

  // Fetch agent prompts, config, and available models when modal opens
  useEffect(() => {
    if (!open) return;

    const fetchData = async () => {
      setLoading(true);
      setError(null);
      setSuccessMessage(null);

      try {
        // Fetch prompts, config, and models in parallel
        const [promptsRes, configRes, modelsRes] = await Promise.all([
          fetch('/api/newsletter/prompts', { credentials: 'include' }),
          fetch('/api/newsletter/config', { credentials: 'include' }),
          fetch('/api/available_models', { credentials: 'include' })
        ]);

        if (!promptsRes.ok) {
          throw new Error(`Failed to fetch prompts: ${promptsRes.status}`);
        }

        const promptsData = await promptsRes.json();
        setAgents(promptsData.prompts || []);

        // Initialize edited content, models, and temps
        const initialContent: Record<string, string> = {};
        const initialModels: Record<string, string> = {};
        const initialTemps: Record<string, string> = {};

        for (const agent of promptsData.prompts || []) {
          initialContent[agent.id] = agent.content;
          initialModels[agent.id] = agent.metadata?.model_config?.model || DEFAULT_MODELS[agent.id] || 'gpt-4.1';
          const temp = agent.metadata?.model_config?.temperature;
          initialTemps[agent.id] = temp !== undefined ? String(temp) : (DEFAULT_TEMPS[agent.id] || '0.3');
        }
        setEditedContent(initialContent);
        setEditedModels(initialModels);
        setEditedTemps(initialTemps);

        // Load global config
        if (configRes.ok) {
          const configData = await configRes.json();
          setEditedTitle(configData.title || 'Weekly Intelligence Digest');
          setEditedIntro(configData.intro || '');
          setEditedDaysBack(configData.days_back || 7);
          setEditedDeepDive(configData.deep_dive_topic || '');

          setOriginalConfig({
            daysBack: configData.days_back || 7,
            deepDiveTopic: configData.deep_dive_topic || '',
            newsletterTitle: configData.title || 'Weekly Intelligence Digest',
            newsletterIntro: configData.intro || ''
          });

          // Update parent state with saved values
          onNewsletterTitleChange(configData.title || 'Weekly Intelligence Digest');
          onNewsletterIntroChange(configData.intro || '');
          onDaysBackChange(configData.days_back || 7);
          onDeepDiveTopicChange(configData.deep_dive_topic || '');
        }

        // Parse available models
        if (modelsRes.ok) {
          const modelsData = await modelsRes.json();
          setAvailableModels(modelsData || []);
        }
      } catch (err) {
        console.error('Error fetching Newsletter data:', err);
        setError(err instanceof Error ? err.message : 'Failed to load data');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [open]);

  // Save all changes (config + agents)
  const saveAll = async () => {
    setSaving(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const savePromises: Promise<Response>[] = [];

      // Save global config if changed
      if (hasConfigChanges()) {
        savePromises.push(
          fetch('/api/newsletter/config', {
            method: 'PUT',
            credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              title: editedTitle,
              intro: editedIntro,
              days_back: editedDaysBack,
              deep_dive_topic: editedDeepDive
            })
          })
        );
      }

      // Save any agents with changes
      for (const agent of agents) {
        if (hasAgentChanges(agent.id)) {
          savePromises.push(
            fetch(`/api/newsletter/prompts/${agent.id}`, {
              method: 'PUT',
              credentials: 'include',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                content: editedContent[agent.id],
                model: editedModels[agent.id],
                temperature: parseFloat(editedTemps[agent.id])
              })
            })
          );
        }
      }

      if (savePromises.length === 0) {
        setSuccessMessage('No changes to save');
        setSaving(false);
        return;
      }

      const results = await Promise.all(savePromises);

      // Check for errors
      const failed = results.filter(r => !r.ok);
      if (failed.length > 0) {
        throw new Error(`Failed to save ${failed.length} item(s)`);
      }

      // Update original config values
      setOriginalConfig({
        daysBack: editedDaysBack,
        deepDiveTopic: editedDeepDive,
        newsletterTitle: editedTitle,
        newsletterIntro: editedIntro
      });

      // Update agents state with saved values
      setAgents(prev => prev.map(a => ({
        ...a,
        content: editedContent[a.id],
        metadata: {
          ...a.metadata,
          model_config: {
            ...a.metadata?.model_config,
            model: editedModels[a.id],
            temperature: parseFloat(editedTemps[a.id])
          }
        }
      })));

      // Update parent state
      onDaysBackChange(editedDaysBack);
      onDeepDiveTopicChange(editedDeepDive);
      onNewsletterTitleChange(editedTitle);
      onNewsletterIntroChange(editedIntro);

      setSuccessMessage('All changes saved successfully');
    } catch (err) {
      console.error('Error saving:', err);
      setError(err instanceof Error ? err.message : 'Failed to save');
    } finally {
      setSaving(false);
    }
  };

  // Reset all changes
  const resetAll = () => {
    // Reset global config
    setEditedDaysBack(originalConfig.daysBack);
    setEditedDeepDive(originalConfig.deepDiveTopic);
    setEditedTitle(originalConfig.newsletterTitle);
    setEditedIntro(originalConfig.newsletterIntro);

    // Reset agent values
    const resetContent: Record<string, string> = {};
    const resetModels: Record<string, string> = {};
    const resetTemps: Record<string, string> = {};

    for (const agent of agents) {
      resetContent[agent.id] = agent.content;
      resetModels[agent.id] = agent.metadata?.model_config?.model || DEFAULT_MODELS[agent.id] || 'gpt-4.1';
      const temp = agent.metadata?.model_config?.temperature;
      resetTemps[agent.id] = temp !== undefined ? String(temp) : (DEFAULT_TEMPS[agent.id] || '0.3');
    }

    setEditedContent(resetContent);
    setEditedModels(resetModels);
    setEditedTemps(resetTemps);
    setSuccessMessage(null);
  };

  // Check if global config has changed
  const hasConfigChanges = () => {
    return editedDaysBack !== originalConfig.daysBack ||
        editedDeepDive !== originalConfig.deepDiveTopic ||
        editedTitle !== originalConfig.newsletterTitle ||
        editedIntro !== originalConfig.newsletterIntro;
  };

  // Check if a specific agent has changes
  const hasAgentChanges = (agentId: string) => {
    const agent = agents.find(a => a.id === agentId);
    if (!agent) return false;

    const contentChanged = editedContent[agentId] !== agent.content;
    const savedModel = agent.metadata?.model_config?.model || DEFAULT_MODELS[agentId];
    const modelChanged = editedModels[agentId] !== savedModel;
    const origTemp = agent.metadata?.model_config?.temperature;
    const savedTemp = origTemp !== undefined ? String(origTemp) : DEFAULT_TEMPS[agentId];
    const tempChanged = editedTemps[agentId] !== savedTemp;

    return contentChanged || modelChanged || tempChanged;
  };

  // Check if ANY changes exist
  const hasAnyChanges = () => {
    if (hasConfigChanges()) return true;
    return agents.some(a => hasAgentChanges(a.id));
  };

  // Get current creativity preset label
  const getCreativityLabel = (temp: string) => {
    const preset = CREATIVITY_PRESETS.find(p => p.value === temp);
    return preset?.label || 'Custom';
  };

  const activeAgentData = agents.find(a => a.id === activeAgent);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[95vw] w-[95vw] h-[90vh] max-h-[90vh] flex flex-col p-0">
        <DialogHeader className="p-6 pb-0 shrink-0">
          <DialogTitle className="text-2xl font-bold flex items-center gap-2">
            <FileText className="w-6 h-6 text-pink-500" />
            Tune: Newsletter
          </DialogTitle>
          <DialogDescription>
            Customize newsletter generation - prompts, models, and settings
          </DialogDescription>
        </DialogHeader>

        {/* Scrollable content area with explicit min-height */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6 min-h-0">
          {/* Newsletter Branding Section */}
          <div className="bg-pink-50 border border-pink-200 rounded-lg p-4">
            <div className="flex items-center justify-between mb-3">
              <label className="text-sm font-semibold text-pink-900">
                Newsletter Branding
              </label>
              {hasConfigChanges() && (
                <span className="text-xs text-orange-600 flex items-center gap-1">
                  <Settings2 className="w-3 h-3" />
                  Modified
                </span>
              )}
            </div>

            <div className="space-y-4">
              {/* Title */}
              <div>
                <Label htmlFor="newsletter-title" className="text-sm font-medium text-pink-800">
                  Newsletter Title
                </Label>
                <Input
                  id="newsletter-title"
                  value={editedTitle}
                  onChange={(e) => setEditedTitle(e.target.value)}
                  placeholder="e.g., Weekly Intelligence Digest"
                  className="mt-1"
                />
              </div>

              {/* Intro/Boilerplate */}
              <div>
                <Label htmlFor="newsletter-intro" className="text-sm font-medium text-pink-800">
                  Introduction / Boilerplate
                </Label>
                <Textarea
                  id="newsletter-intro"
                  value={editedIntro}
                  onChange={(e) => setEditedIntro(e.target.value)}
                  placeholder="e.g., Welcome to this week's intelligence digest..."
                  className="mt-1 min-h-[80px]"
                />
              </div>
            </div>
          </div>

          {/* Generation Settings Section */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <label className="text-sm font-semibold text-blue-900 block mb-3">
              Generation Settings
            </label>

            <div className="flex flex-wrap gap-6">
              {/* Days Back */}
              <div className="w-32">
                <label className="text-xs font-medium text-blue-800 block mb-1">
                  Lookback Period
                </label>
                <p className="text-xs text-blue-600 mb-2">Days to search</p>
                <input
                  type="number"
                  value={editedDaysBack}
                  onChange={(e) => setEditedDaysBack(Math.max(1, Math.min(30, Number(e.target.value))))}
                  min={1}
                  max={30}
                  className="w-full px-3 py-2 border rounded-md text-sm"
                />
              </div>

              {/* Deep Dive Topic */}
              <div className="flex-1 min-w-[200px]">
                <label className="text-xs font-medium text-blue-800 block mb-1">
                  Deep Dive Topic (Optional)
                </label>
                <p className="text-xs text-blue-600 mb-2">Focus for in-depth analysis</p>
                <Input
                  value={editedDeepDive}
                  onChange={(e) => setEditedDeepDive(e.target.value)}
                  placeholder="e.g., AI regulation, Supply chain..."
                />
              </div>
            </div>
          </div>


          {error && (
            <Alert variant="destructive">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {successMessage && (
            <Alert className="bg-green-50 border-green-200">
              <AlertDescription className="text-green-700">{successMessage}</AlertDescription>
            </Alert>
          )}

          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-pink-500" />
              <span className="ml-2 text-gray-600">Loading configuration...</span>
            </div>
          ) : agents.length === 0 ? (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 text-yellow-800">
              <p className="font-medium">No agent prompts found</p>
              <p className="text-sm mt-1">The newsletter agent prompt files may not exist. Check `/data/auspex/agents/` for newsletter_deep_dive_agent.md and newsletter_main_agent.md files.</p>
            </div>
          ) : (
            <>
              {/* Agent Tabs */}
              <div>
                <label className="text-sm font-semibold mb-2 block text-gray-700">Select Agent Step ({agents.length} agents)</label>
                <div className="flex gap-2 flex-wrap">
                  {agents.map((agent) => (
                    <button
                      key={agent.id}
                      onClick={() => setActiveAgent(agent.id)}
                      className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                        activeAgent === agent.id
                          ? 'bg-pink-500 text-white'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {AGENT_ICONS[agent.id]}
                      {agent.name}
                      {hasAgentChanges(agent.id) && (
                        <span className="w-2 h-2 rounded-full bg-orange-400" title="Unsaved changes" />
                      )}
                    </button>
                  ))}
                </div>
              </div>

              {/* Active Agent Settings */}
              {activeAgentData && (
                <>
                  {/* Agent Description & Model Settings */}
                  <div className="bg-gray-50 border rounded-lg p-4">
                    <div className="mb-3">
                      <h3 className="font-semibold text-gray-800">{activeAgentData.name} Agent</h3>
                      <p className="text-sm text-gray-600">{activeAgentData.description}</p>
                    </div>
                    <div className="flex items-center gap-6">
                      {/* Model Selection */}
                      <div>
                        <label className="text-xs font-medium text-gray-500 block mb-1">AI Model</label>
                        <Select
                          value={editedModels[activeAgent] || ''}
                          onValueChange={(value) => setEditedModels(prev => ({ ...prev, [activeAgent]: value }))}
                        >
                          <SelectTrigger className="w-48 h-9">
                            <SelectValue placeholder="Select model" />
                          </SelectTrigger>
                          <SelectContent>
                            {availableModels.map((model) => (
                              <SelectItem key={model.name} value={model.name}>
                                {model.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>

                      {/* Creativity/Temperature Selection */}
                      <div>
                        <label className="text-xs font-medium text-gray-500 block mb-1">Response Style</label>
                        <Select
                          value={editedTemps[activeAgent] || '0.3'}
                          onValueChange={(value) => setEditedTemps(prev => ({ ...prev, [activeAgent]: value }))}
                        >
                          <SelectTrigger className="w-40 h-9">
                            <SelectValue>
                              {getCreativityLabel(editedTemps[activeAgent])}
                            </SelectValue>
                          </SelectTrigger>
                          <SelectContent>
                            {CREATIVITY_PRESETS.map((preset) => (
                              <SelectItem key={preset.value} value={preset.value}>
                                <div className="flex flex-col">
                                  <span className="font-medium">{preset.label}</span>
                                  <span className="text-gray-500 text-xs">{preset.description}</span>
                                </div>
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </div>

                  {/* Prompt Editor */}
                  <div>
                    <label className="text-sm font-semibold mb-2 block text-gray-700">Agent Instructions</label>
                    <p className="text-xs text-gray-500 mb-2">
                      The prompt that guides how this agent performs its task
                    </p>
                    <textarea
                      value={editedContent[activeAgent] || ''}
                      onChange={(e) => setEditedContent(prev => ({
                        ...prev,
                        [activeAgent]: e.target.value
                      }))}
                      className="w-full h-[400px] p-4 border rounded-lg font-mono text-xs leading-relaxed resize-y"
                      placeholder="Agent prompt content..."
                    />
                  </div>
                </>
              )}

              {/* Save/Reset Buttons */}
              <div className="flex items-center justify-between pt-4 border-t">
                <div className="text-sm text-gray-500">
                  {hasAnyChanges() ? (
                    <span className="text-orange-600 flex items-center gap-1">
                      <Settings2 className="w-4 h-4" />
                      Unsaved changes
                    </span>
                  ) : (
                    <span className="text-green-600">All settings saved</span>
                  )}
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={resetAll}
                    disabled={!hasAnyChanges()}
                    className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <RotateCcw className="w-4 h-4 inline mr-2" />
                    Reset All
                  </button>
                  <button
                    onClick={saveAll}
                    disabled={!hasAnyChanges() || saving}
                    className="px-4 py-2 bg-pink-500 text-white hover:bg-pink-600 rounded-md text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {saving ? (
                      <Loader2 className="w-4 h-4 inline mr-2 animate-spin" />
                    ) : (
                      <Save className="w-4 h-4 inline mr-2" />
                    )}
                    Save All
                  </button>
                  <button
                    onClick={() => onOpenChange(false)}
                    className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md text-sm font-medium"
                  >
                    Close
                  </button>
                </div>
              </div>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
