#!/usr/bin/env python3
"""Provision (or destroy) a dedicated Brand Watcher tenant from the golden template.

Stamps out a full tenant from bwtemplate.aunoo.ai: directory + venv clone,
database restore from the golden dump, encrypted .env, systemd unit,
nginx + Let's Encrypt, then seeds the customer brand through the app's own
API (POST /brands + /brands/{id}/setup-monitoring) and verifies the result.

Run as root. Stdlib only. See docs/BRAND_WATCHER_TENANT_TEMPLATE.md.

Examples:
    provision_brand_tenant.py provision --slug acme --brand "Acme Publishing" \
        --aliases "Acme Corp,ACME" --keywords "Acme Publishing,Acme Press"
    provision_brand_tenant.py provision --slug acme --brand "Acme" --skip-nginx
    provision_brand_tenant.py destroy --slug acme --yes
"""

import argparse
import http.cookiejar
import json
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.parse
import urllib.request

TENANTS_DIR = "/home/orochford/tenants"
TEMPLATE_DIR = os.path.join(TENANTS_DIR, "bwtemplate.aunoo.ai")
TEMPLATE_DUMP = "/var/tmp/bw_template.dump"
TEMPLATE_UNIT = "/etc/systemd/system/bwtemplate.aunoo.ai.service"
ENV_TOOL = ["/home/orochford/bin/.venv/bin/python3", "/home/orochford/bin/env_encryption.py"]
SHARED_MODELS = "/home/orochford/shared-models"
OWNER = "orochford"
PORT_RANGE = range(10018, 10100)

RSYNC_EXCLUDES = [
    # "/models" without trailing slash: the template's models is a SYMLINK,
    # and "/models/" would only match a directory. Anchored, so app/models
    # (the ORM package) is not affected.
    "/models", "/cache/", "/chromadb/", "/logs/", ".venv/", ".git/",
    ".env", ".env.encrypted", "ui/node_modules/", "__pycache__/", "*.pyc",
    "/webninjakey", "/xpozkey",
]

NGINX_SITE_TEMPLATE = """# Auto-generated by provision_brand_tenant.py (HTTP-only until Certbot runs)
server {{
    listen 80;
    server_name {domain};

    # ACME challenges
    location ^~ /.well-known/acme-challenge/ {{
        root /var/www/letsencrypt;
    }}

    location / {{
        proxy_pass         http://127.0.0.1:{port};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }}
}}
"""


def log(msg):
    print(f"[provision] {msg}", flush=True)


def die(msg, code=1):
    print(f"[provision] ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(code)


def run(cmd, check=True, capture=False, **kw):
    log("$ " + " ".join(cmd))
    return subprocess.run(cmd, check=check, text=True,
                          capture_output=capture, **kw)


def psql(sql, db="postgres", capture=True):
    r = run(["sudo", "-u", "postgres", "psql", "-d", db, "-v", "ON_ERROR_STOP=1",
             "-tAc", sql], capture=capture)
    return r.stdout.strip() if capture else None


def names(slug):
    return {
        "slug": slug,
        "dir": os.path.join(TENANTS_DIR, f"{slug}.aunoo.ai"),
        "db": slug,
        "db_user": f"{slug}_user",
        "domain": f"{slug}.aunoo.ai",
        "unit": f"{slug}.aunoo.ai.service",
        "unit_path": f"/etc/systemd/system/{slug}.aunoo.ai.service",
        "nginx_avail": f"/etc/nginx/sites-available/{slug}.aunoo.ai",
        "nginx_enabled": f"/etc/nginx/sites-enabled/{slug}.aunoo.ai",
        "creds": f"/var/tmp/{slug}_credentials.txt",
    }


def port_in_use(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


def pick_port():
    for p in PORT_RANGE:
        if not port_in_use(p):
            return p
    die("no free port in range")


def wait_for_port(port, timeout=180):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if port_in_use(port):
            return True
        time.sleep(3)
    return False


# ---------------------------------------------------------------------------
# HTTP client for seeding through the app's API
# ---------------------------------------------------------------------------

class TenantClient:
    def __init__(self, port):
        self.base = f"http://127.0.0.1:{port}"
        self.opener = urllib.request.build_opener(
            urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))

    def _request(self, path, data=None, as_json=False, method=None):
        headers = {"X-Forwarded-Proto": "https"}
        body = None
        if data is not None:
            if as_json:
                body = json.dumps(data).encode()
                headers["Content-Type"] = "application/json"
            else:
                body = urllib.parse.urlencode(data).encode()
        req = urllib.request.Request(self.base + path, data=body,
                                     headers=headers, method=method)
        try:
            with self.opener.open(req, timeout=60) as resp:
                return resp.status, resp.read().decode()
        except urllib.error.HTTPError as e:
            return e.code, e.read().decode()

    def login(self, username, password):
        status, _ = self._request("/login", {"username": username, "password": password})
        # 200 = followed redirect chain; a session cookie is set either way
        if status not in (200, 302, 303, 307):
            die(f"login failed with HTTP {status}")

    def get_json(self, path):
        status, body = self._request(path)
        if status != 200:
            die(f"GET {path} -> HTTP {status}: {body[:300]}")
        return json.loads(body)

    def post_json(self, path, payload):
        status, body = self._request(path, payload, as_json=True)
        if status not in (200, 201):
            die(f"POST {path} -> HTTP {status}: {body[:300]}")
        return json.loads(body)


# ---------------------------------------------------------------------------
# Provision
# ---------------------------------------------------------------------------

def read_template_env():
    """Return the template's plaintext .env content (decrypting a copy if needed)."""
    env_path = os.path.join(TEMPLATE_DIR, ".env")
    if os.path.exists(env_path):
        return open(env_path).read()
    enc_path = env_path + ".encrypted"
    if not os.path.exists(enc_path):
        die(f"template has neither .env nor .env.encrypted in {TEMPLATE_DIR}")
    run(["sudo", "-u", OWNER] + ENV_TOOL + ["decrypt", TEMPLATE_DIR])
    content = open(env_path).read()
    os.remove(env_path)  # leave the template encrypted-at-rest
    return content


def render_env(template_env, n, port, db_password):
    subs = {
        "PORT": str(port),
        "DOMAIN": n["domain"],
        "DB_NAME": n["db"],
        "DB_USER": n["db_user"],
        "DB_PASSWORD": db_password,
        "DATABASE_URL": f"postgresql+asyncpg://{n['db_user']}:{db_password}@localhost:5432/{n['db']}",
        "SYNC_DATABASE_URL": f"postgresql+psycopg2://{n['db_user']}:{db_password}@localhost:5432/{n['db']}",
        "FLASK_SECRET_KEY": secrets.token_hex(32),
        "NORN_SECRET_KEY": secrets.token_hex(32),
    }
    out = []
    for line in template_env.splitlines():
        key = line.split("=", 1)[0] if "=" in line else None
        out.append(f"{key}={subs[key]}" if key in subs else line)
    return "\n".join(out) + "\n"


def provision(args):
    if os.geteuid() != 0:
        die("must run as root")
    slug = args.slug
    if not re.fullmatch(r"[a-z][a-z0-9]{1,30}", slug):
        die("slug must be lowercase alphanumeric, starting with a letter")
    n = names(slug)

    # Preflight
    for path in (TEMPLATE_DIR, args.dump, TEMPLATE_UNIT):
        if not os.path.exists(path):
            die(f"missing prerequisite: {path}")
    if os.path.exists(n["dir"]):
        die(f"{n['dir']} already exists")
    if os.path.exists(n["unit_path"]):
        die(f"{n['unit_path']} already exists")
    if psql(f"SELECT 1 FROM pg_database WHERE datname='{n['db']}'"):
        die(f"database {n['db']} already exists")
    port = args.port or pick_port()
    if port_in_use(port):
        die(f"port {port} is in use")
    log(f"provisioning {n['domain']} on port {port}")

    # 1. Directory + venv + models symlink
    excludes = [f"--exclude={e}" for e in RSYNC_EXCLUDES]
    run(["rsync", "-a"] + excludes + [TEMPLATE_DIR + "/", n["dir"] + "/"])
    run(["rsync", "-a", os.path.join(TEMPLATE_DIR, ".venv") + "/",
         os.path.join(n["dir"], ".venv") + "/"])
    os.makedirs(os.path.join(n["dir"], "logs"), exist_ok=True)
    models_link = os.path.join(n["dir"], "models")
    if os.path.lexists(models_link):
        os.remove(models_link)
    os.symlink(SHARED_MODELS, models_link)
    run(["chown", "-R", f"{OWNER}:{OWNER}", os.path.join(n["dir"], "logs")])
    run(["chown", "-h", f"{OWNER}:{OWNER}", os.path.join(n["dir"], "models")])
    # Guard against the unanchored-exclude footgun (app/models must survive)
    if not os.path.isdir(os.path.join(n["dir"], "app", "models")):
        die("app/models missing after rsync — check excludes")

    # 2. Database
    db_password = secrets.token_hex(24)
    psql(f"CREATE ROLE {n['db_user']} LOGIN PASSWORD '{db_password}'", capture=False)
    run(["sudo", "-u", "postgres", "createdb", "-O", n["db_user"], n["db"]])
    psql("CREATE EXTENSION vector", db=n["db"], capture=False)
    r = run(["sudo", "-u", "postgres", "pg_restore", "--no-owner",
             f"--role={n['db_user']}", "-j4", "-d", n["db"], args.dump],
            check=False, capture=True)
    benign = [l for l in (r.stderr or "").splitlines()
              if "must be owner of extension vector" not in l and l.strip()
              and "errors ignored on restore" not in l and "Command was:" not in l]
    if r.returncode != 0 and benign:
        die("pg_restore failed:\n" + "\n".join(benign[:10]))
    tables = psql("SELECT count(*) FROM information_schema.tables WHERE table_schema='public'", db=n["db"])
    if int(tables) < 100:
        die(f"restore produced only {tables} tables")
    log(f"database restored ({tables} tables)")

    # 3. .env (plaintext -> encrypted at rest)
    env_content = render_env(read_template_env(), n, port, db_password)
    env_path = os.path.join(n["dir"], ".env")
    with open(env_path, "w") as f:
        f.write(env_content)
    os.chmod(env_path, 0o600)
    run(["chown", f"{OWNER}:{OWNER}", env_path])
    run(["sudo", "-u", OWNER] + ENV_TOOL + ["encrypt", n["dir"]])
    run(["sudo", "-u", OWNER] + ENV_TOOL + ["verify", n["dir"]])

    # 4. Admin password (dump ships force_password_change=true, onboarding done)
    admin_password = secrets.token_urlsafe(12)
    hash_cmd = [os.path.join(n["dir"], ".venv/bin/python"), "-c",
                "from passlib.context import CryptContext; import sys; "
                "print(CryptContext(schemes=['bcrypt'], bcrypt__ident='2b').hash(sys.argv[1]))",
                admin_password]
    admin_hash = run(hash_cmd, capture=True).stdout.strip()
    psql(f"UPDATE users SET password_hash='{admin_hash}', force_password_change=true "
         f"WHERE username='admin'", db=n["db"], capture=False)

    # 5. systemd
    unit = open(TEMPLATE_UNIT).read().replace("bwtemplate.aunoo.ai", n["domain"]) \
                                     .replace("FastAPI bwtemplate", f"FastAPI {slug}")
    with open(n["unit_path"], "w") as f:
        f.write(unit)
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "--now", n["unit"]])
    if not wait_for_port(port):
        run(["journalctl", "-u", n["unit"], "-n", "30", "--no-pager"], check=False)
        die(f"service did not start listening on {port}")
    log("service is up")

    # 6. nginx + TLS
    if not args.skip_nginx:
        with open(n["nginx_avail"], "w") as f:
            f.write(NGINX_SITE_TEMPLATE.format(domain=n["domain"], port=port))
        if not os.path.exists(n["nginx_enabled"]):
            os.symlink(n["nginx_avail"], n["nginx_enabled"])
        run(["nginx", "-t"])
        run(["systemctl", "reload", "nginx"])
        run(["certbot", "--nginx", "-d", n["domain"], "--email", args.email,
             "--agree-tos", "--non-interactive", "--redirect"])
        log(f"https://{n['domain']} is live")

    # 7. Seed the brand through the app's own API
    client = TenantClient(port)
    client.login("admin", admin_password)
    modules = client.get_json("/api/modules")
    if not modules.get("dedicated_mode"):
        die("tenant is not in dedicated mode — check BW_DEDICATED_MODE in .env")
    keywords = [k.strip() for k in (args.keywords or "").split(",") if k.strip()]
    aliases = [a.strip() for a in (args.aliases or "").split(",") if a.strip()]
    brand_keywords = list(dict.fromkeys([args.brand] + aliases + keywords))
    brand = client.post_json("/api/brand-watcher/brands", {
        "name": slug,
        "display_name": args.brand,
        "description": f"Primary monitored brand for {n['domain']}",
        "brand_keywords": brand_keywords,
    })
    brand_id = brand["id"]
    setup = client.post_json(f"/api/brand-watcher/brands/{brand_id}/setup-monitoring", {})
    log(f"brand {brand_id} seeded: topic '{setup.get('topic_name')}', "
        f"group '{setup.get('group_name')}'")

    # 8. Verify
    brands = client.get_json("/api/brand-watcher/brands")
    assert any(b["id"] == brand_id for b in brands), "brand missing after seed"
    arts = client.get_json("/api/brand-watcher/articles?days=30")
    assert arts.get("total_count") == 0, "expected empty article set"
    log("verification passed: dedicated mode on, brand seeded, clean empty state")

    # 9. Record credentials (root-only)
    with open(n["creds"], "w") as f:
        f.write(f"tenant: {n['domain']} (port {port})\n"
                f"db: {n['db']} / {n['db_user']} / {db_password}\n"
                f"admin password: {admin_password} (change forced on first login)\n")
    os.chmod(n["creds"], 0o600)
    log(f"credentials written to {n['creds']}")
    log(f"DONE: https://{n['domain']} — log in as admin, add users, tune the "
        f"brand keywords in the Brand Watcher config tab")


# ---------------------------------------------------------------------------
# Destroy
# ---------------------------------------------------------------------------

def destroy(args):
    if os.geteuid() != 0:
        die("must run as root")
    n = names(args.slug)
    if n["dir"].rstrip("/") in (TEMPLATE_DIR, os.path.join(TENANTS_DIR, "bugfixing.aunoo.ai"),
                                os.path.join(TENANTS_DIR, "wiley.aunoo.ai"),
                                os.path.join(TENANTS_DIR, "wileytest.aunoo.ai")):
        die("refusing to destroy a protected tenant")
    if not args.yes:
        die("destroy requires --yes")
    log(f"destroying {n['domain']}")
    run(["systemctl", "disable", "--now", n["unit"]], check=False)
    if os.path.exists(n["unit_path"]):
        os.remove(n["unit_path"])
        run(["systemctl", "daemon-reload"])
    for p in (n["nginx_enabled"], n["nginx_avail"]):
        if os.path.exists(p) or os.path.islink(p):
            os.remove(p)
    run(["nginx", "-t"], check=False)
    run(["systemctl", "reload", "nginx"], check=False)
    run(["certbot", "delete", "--cert-name", n["domain"], "--non-interactive"], check=False)
    psql(f"DROP DATABASE IF EXISTS {n['db']} WITH (FORCE)", capture=False)
    psql(f"DROP ROLE IF EXISTS {n['db_user']}", capture=False)
    if os.path.isdir(n["dir"]):
        shutil.rmtree(n["dir"])
    if os.path.exists(n["creds"]):
        os.remove(n["creds"])
    log(f"destroyed {n['domain']}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("provision", help="stamp out a new dedicated BW tenant")
    p.add_argument("--slug", required=True, help="tenant slug (dir/db/user/domain prefix)")
    p.add_argument("--brand", required=True, help="brand display name, e.g. 'Acme Publishing'")
    p.add_argument("--aliases", help="comma-separated brand aliases (legal names, tickers)")
    p.add_argument("--keywords", help="comma-separated extra monitoring keywords")
    p.add_argument("--port", type=int, help=f"backend port (default: first free in {PORT_RANGE.start}-{PORT_RANGE.stop - 1})")
    p.add_argument("--email", default="oliver.rochford@gmail.com", help="certbot contact email")
    p.add_argument("--dump", default=TEMPLATE_DUMP, help="golden template dump")
    p.add_argument("--skip-nginx", action="store_true", help="skip nginx + certbot (local testing)")
    p.set_defaults(func=provision)

    d = sub.add_parser("destroy", help="tear a tenant down completely")
    d.add_argument("--slug", required=True)
    d.add_argument("--yes", action="store_true", help="confirm destruction")
    d.set_defaults(func=destroy)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
